name: SuperParties
version: "1.0.0"
main: me.superpenguin.superparties.SuperParties
api-version: '1.20'
authors: [SuperPenguin]
description: Party plugin with extensible API!

libraries:
  - net.kyori:adventure-text-minimessage:4.14.0
  - net.kyori:adventure-platform-bukkit:4.3.0